import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.join(__dirname, "..");
const configPath = path.join(projectRoot, "public", "config.js");

const mode = (process.argv[2] || "").toLowerCase();
if (!["web", "ios"].includes(mode)) {
  console.error("Usage: node scripts/write_config.js <web|ios>");
  process.exit(1);
}

const adsClientDefault = "ca-pub-6736669949964710";
const adsSlotDefault = "";

const apiBase =
  mode === "web"
    ? (process.env.WEB_API_BASE || "").trim()
    : (process.env.IOS_API_BASE || process.env.API_BASE || "").trim();

const adsClient =
  mode === "web"
    ? (process.env.ADSENSE_CLIENT || adsClientDefault).trim()
    : "";

const adsSlot =
  mode === "web" ? (process.env.ADSENSE_SLOT || adsSlotDefault).trim() : "";

const content = `/**
 * Auto-generated by scripts/write_config.js (${mode} mode).
 * Do not hand-edit in normal workflow.
 */

/**
 * API base URL.
 * - "" = same origin (recommended when the HTML is served by this Express app).
 * - For Capacitor / another host: full URL with scheme, e.g. "https://your-app.up.railway.app"
 *   (host-only strings are auto-fixed to https:// in apiBase.js).
 */
window.__API_BASE__ = ${JSON.stringify(apiBase)};

/**
 * Google AdSense (web only). Leave empty until AdSense approves your site.
 * Example client: ca-pub-xxxxxxxxxxxxxxxx
 */
window.__ADSENSE_CLIENT__ = ${JSON.stringify(adsClient)};

/**
 * Ad unit slot id from AdSense (required with client to show a display unit).
 */
window.__ADSENSE_SLOT__ = ${JSON.stringify(adsSlot)};
`;

fs.writeFileSync(configPath, content, "utf8");
console.log(`Wrote public/config.js for ${mode} mode`);
