import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.join(__dirname, "..");
const configPath = path.join(projectRoot, "public", "config.js");

const mode = (process.argv[2] || "").toLowerCase();
if (!["web", "ios"].includes(mode)) {
  console.error("Usage: node scripts/write_config.js <web|ios>");
  process.exit(1);
}

const adsClientDefault = "ca-pub-6736669949964710";
const adsSlotDefault = "";
const admobAppIdTest = "ca-app-pub-3940256099942544~1458002511";
const admobBannerIdTest = "ca-app-pub-3940256099942544/2435281174";
const iapProductIdDefault = "com.timezonemeet.app.premium";

const apiBase =
  mode === "web"
    ? (process.env.WEB_API_BASE || "").trim()
    : (process.env.IOS_API_BASE || process.env.API_BASE || "").trim();

const adsClient =
  mode === "web"
    ? (process.env.ADSENSE_CLIENT || adsClientDefault).trim()
    : "";

const adsSlot =
  mode === "web" ? (process.env.ADSENSE_SLOT || adsSlotDefault).trim() : "";

const admobEnabled = mode === "ios";
const admobIosAppId =
  mode === "ios" ? (process.env.IOS_ADMOB_APP_ID || admobAppIdTest).trim() : "";
const admobBannerId =
  mode === "ios"
    ? (process.env.IOS_ADMOB_BANNER_ID || admobBannerIdTest).trim()
    : "";
const admobTestMode =
  mode === "ios"
    ? !["0", "false", "no", "off"].includes(
        String(process.env.IOS_ADMOB_TEST_MODE || "1").toLowerCase()
      )
    : false;

const iapEnabled = mode === "ios";
const iapProductId =
  mode === "ios"
    ? (process.env.IOS_IAP_PRODUCT_ID || iapProductIdDefault).trim()
    : "";

const content = `/**
 * Auto-generated by scripts/write_config.js (${mode} mode).
 * Do not hand-edit in normal workflow.
 */

/**
 * API base URL.
 * - "" = same origin (recommended when the HTML is served by this Express app).
 * - For Capacitor / another host: full URL with scheme, e.g. "https://your-app.up.railway.app"
 *   (host-only strings are auto-fixed to https:// in apiBase.js).
 */
window.__API_BASE__ = ${JSON.stringify(apiBase)};

/**
 * Google AdSense (web only). Leave empty until AdSense approves your site.
 * Example client: ca-pub-xxxxxxxxxxxxxxxx
 */
window.__ADSENSE_CLIENT__ = ${JSON.stringify(adsClient)};

/**
 * Ad unit slot id from AdSense (required with client to show a display unit).
 */
window.__ADSENSE_SLOT__ = ${JSON.stringify(adsSlot)};

/**
 * AdMob (iOS native via Capacitor plugin).
 * Defaults to Google's test ids in ios mode.
 */
window.__ADMOB_ENABLED__ = ${JSON.stringify(admobEnabled)};
window.__ADMOB_IOS_APP_ID__ = ${JSON.stringify(admobIosAppId)};
window.__ADMOB_BANNER_ID__ = ${JSON.stringify(admobBannerId)};
window.__ADMOB_TEST_MODE__ = ${JSON.stringify(admobTestMode)};

/**
 * Apple In‑App Purchase (iOS native via cordova-plugin-purchase).
 */
window.__IAP_ENABLED__ = ${JSON.stringify(iapEnabled)};
window.__IAP_PRODUCT_ID__ = ${JSON.stringify(iapProductId)};
`;

fs.writeFileSync(configPath, content, "utf8");
console.log(`Wrote public/config.js for ${mode} mode`);
